#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

: "${MARKED_NORMAL_BCOLOR:=0x0000ff}"
: "${MARKED_ACTIVE_BCOLOR:=0x00ff00}"
: "${MARKED_FOCUSED_BCOLOR:=0xff0000}"

while bspc subscribe -c 1 node_focus node_flag > /dev/null; do
    bspc config focused_border_color "$(bspc config focused_border_color)"

    bspc query -N -n '.marked.!focused.window' | while read -r wid; do
        chwb -c "$MARKED_NORMAL_BCOLOR" "$wid"
    done
    bspc query -N -n '.marked.active.!focused.window' | while read -r wid; do
        chwb -c "$MARKED_ACTIVE_BCOLOR" "$wid"
    done
    bspc query -N -n "focused.marked" | while read -r wid; do
        chwb -c "$MARKED_FOCUSED_BCOLOR" "$wid"
    done
done
